Graviti-AI/graviti-python-sdk

graviti/utility/lazy.py
`numpy.fromiter` does not support creating object arrays from iterator.
=> refactor(utility): replace np.fromiter with np.array

graviti/openapi/branch.py, graviti/openapi/commit.py, graviti/openapi/dataset.py, graviti/openapi/draft.py, graviti/openapi/request.py, graviti/openapi/tag.py
"https://graviti.com/api/v1/" -> "https://api.graviti.com/v2/"
=> refactor(openapi): update the prefix and version of openapi request url

graviti/openapi/branch.py, graviti/openapi/commit.py, graviti/openapi/dataset.py, graviti/openapi/draft.py, graviti/openapi/tag.py
{dataset} -> {owner}/{dataset}
=> refactor(openapi): add dataset owner to request url

graviti/utility/lazy2.py
Make "PagingList" manage both lazy and non-lazy data.
- remove "LazyFactory.from_array"
- add "PagingList.from_factory"
=> refactor(utility): rename "LazyList" to "PagingList"

graviti/dataframe/column/indexing.py, graviti/dataframe/column/series.py, graviti/dataframe/frame.py, graviti/dataframe/indexing.py
Stop supporting functions:
- `DataFrame.loc`
- `DataFrame.iloc`
- `Series.loc`
- `Series.iloc`
- `Series.__getitem__`
=> feat(dataframe): stop supporting Iterable[int] input for "__getitem__"

graviti/utility/paging.py
```
ValueError: range() arg 3 must not be zero
```
=> fix(utility): fix the ValueError calling "extend" in empty "PagingList"

graviti/dataframe/frame.py
The error scene:
```python
import graviti.portex as pt
from graviti import DataFrame
schema = pt.record(
{
"attribute": pt.record(
{
"truncated": pt.boolean(),
}
)
}
)
data = [
{"attribute": {"truncated": False}},
{"attribute": {"truncated": False}}
]
df = DataFrame(data=data, schema=schema)
```
TypeError: string indices must be integers
=> fix(dataframe): fix TypeError when create a MultiIndex DataFrame

graviti/portex/template.py
url: https://github.com/Project-OpenBytes/portex
commit: ab85623742f499d81be195931b1f0f1a16ca74a9
=> docs(portex): update the template docstring to adapt Portex "ab85623"

graviti/manager/branch.py, graviti/manager/commit.py, graviti/manager/dataset.py, graviti/manager/draft.py, graviti/manager/tag.py, graviti/openapi/branch.py, graviti/openapi/commit.py, graviti/openapi/data.py, graviti/openapi/dataset.py, graviti/openapi/draft.py, graviti/openapi/search.py, graviti/openapi/sheet.py, graviti/openapi/tag.py
offset in openapi: 0 -> None
limit in openapi: 128 -> None
limit in manager(except for list data): 128 -> 24
=> refactor: modify the default value of "offset" and "limit"

graviti/portex/package.py
The main purpose is to avoid name collision of different repos.
=> refactor(portex): use the checksum of url + revision as the repo path

graviti/openapi/branch.py, graviti/openapi/commit.py, graviti/openapi/data.py, graviti/openapi/dataset.py, graviti/openapi/draft.py, graviti/openapi/schema.py, graviti/openapi/search.py, graviti/openapi/sheet.py, graviti/openapi/tag.py, graviti/openapi/user.py, graviti/workspace.py
"https://api.graviti.com" ->
"https://gas.graviti.com/gatewayv2/tensorbay-open-api"
=> refactor: modify the url predix of OpenAPIv2

graviti/openapi/branch.py, graviti/openapi/commit.py, graviti/openapi/data.py, graviti/openapi/dataset.py, graviti/openapi/draft.py, graviti/openapi/schema.py, graviti/openapi/search.py, graviti/openapi/sheet.py, graviti/openapi/tag.py, graviti/openapi/user.py, graviti/workspace.py
This reverts commit 272ece9e60cce1565c79052bb1e3d5962d8c610b.
=> Revert "refactor: modify the url predix of OpenAPIv2"

graviti/portex/builder.py
Both full or short commit id are supported
=> feat(portex): support building package when the revision is commit id

graviti/manager/branch.py, graviti/manager/commit.py, graviti/manager/common.py, graviti/manager/draft.py, graviti/manager/tag.py
- create branch
- list branches
- get branch
- create draft
- list commits
- get commit
- create tag
- list tags
- get tag
=> feat(manager): add "check_head_status" to some methods in "manager"

graviti/manager/branch.py, graviti/manager/commit.py, graviti/manager/common.py, graviti/manager/draft.py, graviti/manager/tag.py
To make it easier for the user to understand, use class "DefaultValue" instead
of None to represent the default value of parameters from methods in manager.
=> refactor(manager): add class "DefaultValue" to "common.py"

docs/source/getting_started/10_minutes_to_graviti.rst
Useless parts:
- sign up in Graviti website
- version control
- list sheets
=> docs: remove useless parts from "10_minutes_to_graviti.rst"

graviti/manager/branch.py, graviti/manager/commit.py, graviti/manager/common.py, graviti/manager/dataset.py, graviti/manager/draft.py, graviti/manager/sheets.py, graviti/manager/tag.py, graviti/openapi/branch.py, graviti/openapi/commit.py, graviti/openapi/dataset.py, graviti/openapi/draft.py, graviti/openapi/sheet.py, graviti/openapi/tag.py
Add constant "LIMIT" to "manager/common.py" to represent the default
value of parameter "limit".
=> refactor: change the default value of "limit" from 24 to 128

README.md, docs/source/getting_started/10_minutes_to_graviti.rst, graviti/openapi/branch.py, graviti/openapi/commit.py, graviti/openapi/data.py, graviti/openapi/dataset.py, graviti/openapi/draft.py, graviti/openapi/schema.py, graviti/openapi/search.py, graviti/openapi/sheet.py, graviti/openapi/tag.py, graviti/openapi/user.py
=> docs: use "Graviti-example" as the user name in example code

docs/source/features/dataset_management.rst, docs/source/features/version_control/branch.rst, docs/source/features/version_control/commit.rst, docs/source/features/version_control/draft.rst, docs/source/features/version_control/tag.rst
Split a whole block of example code and add explanations for different input
parameters to improve the readability.
=> docs: add descriptions to the example codes in "FEATURES"

graviti/dataframe/frame.py
TypeError: Unsupported column type:
<class 'graviti.dataframe.column.series.ArraySeries'>
=> fix(dataframe): fix the "Unsupported column type" in DataFrame.__repr__

docs/source/features/sheet_management/index.rst
- delete the operations on revision
- add description about dict
- add replace sheet
=> docs: modify the documentation about "Sheet Management"

graviti/portex/factory.py, graviti/portex/field.py
1. Rename "ImmutableFields" to "FrozenFields".
2. Remove "MutableFields".
=> refactor(portex): rename "ImmutableFields" and remove "MutableFields"

graviti/portex/base.py, graviti/portex/external.py
| cases                  | before              | after              |
| ---------------------- | ------------------- | ------------------ |
| std.label.Box2D()      | 135 µs ± 279 ns     | 27.1 µs ± 244 ns   |
| std.label.Box3D()      | 280 µs ± 4.56 µs    | 27.1 µs ± 298 ns   |
=> refactor(portex): make "container" in "PortexType" to "ClassVar"

graviti/utility/repr.py
1. add type hint to variable "class_" to remove the pyright warning
2. remove useless pylint disable "protected-access"
=> style(utility): add type hint and remove pylint comment in "repr._repr1"

requirements.txt, setup.cfg
Added dependencies:
- requests_toolbelt
- typing_extension
- tqdm
=> build: remove tensorbay dependency and add supplemented dependencies

graviti/paging/lists.py, graviti/paging/page.py
Get the source array by calling the "array_getter" directly.
=> refactor(paging): remove the "_pos" attr in "LazyPage"

graviti/dataframe/column/series.py
The error message:
AttributeError: 'pyarrow.lib.ListScalar' object has no attribute 'field'
=> fix(dataframe): fix the "AttributeError" when reading nested DataFrame

.gitlint, .pre-commit-config.yaml
- remove the commit type "revert"
- use CT1: contrib-title-conventional-commits to check Conventional Commits
=> ci: update "gitlint" version to "v0.17.0"

graviti/portex/field.py
This reverts commit 1b6516ed85ed8130062f47a85693ae09840a57a2.
=> Revert "feat(portex): restrict cased characters in the "Fields" key be lowercase"

graviti/dataframe/frame.py
example:
```python
In [8]: schema  # the array items is enum
Out[8]:
record(
fields={
'a': array(
items=enum(
values=['cat', 'dog'],
),
),
},
)
In [9]: data  # the first array is an empty list
Out[9]:
[{'a': []},
{'a': ['cat', 'dog']},
{'a': ['cat', 'dog']},
{'a': ['cat', 'dog']}]
In [10]: DataFrame(data, schema)  # creation fail
---------------------------------------------------------------------------
ArrowInvalid                              Traceback (most recent call last)
...
...
ArrowInvalid: Could not convert 'cat' with type str: tried to convert to int8
```
=> fix(dataframe): fix DataFrame creation fail when the array items is enum

graviti/paging/factory.py, graviti/paging/wrapper.py
Error Message:
AttributeError: 'StructScalarWrapper' object has no attribute 'as_py'
=> fix(paging): fix the AttributeError caused by "StructScalarWrapper"

graviti/portex/avro.py
- remove useless "index" parameter
- use "_on_struct" method to process first "record"
- use "skip_url" flag to handle the "url" field in "std.file.RemoteFile"
=> refactor(portex): refine the logic of "convert_portex_schema_to_avro"

docs/source/features/sheet_management/binary_files.rst
- For text file: ".text" -> ".txt"
- For audio file: ".mp3" -> ".wav"
- For point cloud file: None -> ".pcd"
=> docs: correct the filename extensions in "binary_files.rst"

graviti/paging/lists.py
- `PagingListBase._get_item` -> `PagingListBase.get_item`
- `PagingListBase._get_slice` -> `PagingListBase.get_slice`
=> refactor(paging): change "_get_item" and "_get_slice" to public methods

graviti/dataframe/sql/array.py, graviti/dataframe/sql/scalar.py
separate `ComparisonArithmeticOperatorsMixin` to:
- `ComparisonOperatorsMixin`
- `ArithmeticOperatorsMixin`
=> refactor(dataframe): separate "ComparisonArithmeticOperatorsMixin"

graviti/dataframe/sql/array.py, graviti/dataframe/sql/scalar.py
separate `LogicalOperatorsMixin` to:
- `LogicalOperatorsMixin`
- `EqualOperatorsMixin`
=> refactor(dataframe): separate "LogicalOperatorsMixin"

graviti/dataframe/sql/array.py, graviti/dataframe/sql/scalar.py
Error Message:
AttributeError: 'int' object has no attribute 'schema'
=> fix(dataframe): fix the "AttributeError" when searching with constant

graviti/__init__.py, graviti/dataframe/__init__.py, graviti/dataframe/column/indexing.py, graviti/dataframe/column/series.py, graviti/dataframe/frame.py, graviti/dataframe/indexing.py
In "colmun/series.py":
- Rename:
- `SeriesBase` -> `Series`
- `Series` -> `PyarrowSeries`
- Add:
- `NumberSeries`
- `StringSeries`
- `BinarySeries`
=> refactor(dataframe): adjust the inheritance relationship for series

graviti/dataframe/column/series.py, graviti/dataframe/frame.py, graviti/portex/base.py, graviti/portex/builtin.py
Support converting "pa.dictionary" to "pt.enum"
=> refactor(portex): use pa.Array as the input of PortexType.from_pyarrow

graviti/dataframe/column/series.py, graviti/dataframe/frame.py, graviti/manager/commit.py, graviti/manager/draft.py, graviti/manager/sheets.py, graviti/portex/base.py, graviti/portex/builtin.py, graviti/portex/enum.py, graviti/portex/external.py, graviti/portex/field.py
Support converting "pt.enum" to "pa.dictionary"
=> refactor(dataframe): add _to_backend parameter to PortexType.to_pyarrow

graviti/openapi/__init__.py, graviti/openapi/storage_config.py
Add the following funcions:
- `get_storage_config`
- `list_storage_configs`
- `update_storage_configs`
=> feat(openapi): implement "storage config" related OpenAPI functions

graviti/openapi/__init__.py, graviti/openapi/search.py
Add the following funcions:
- `create_search_history`
- `get_search_history`
- `list_search_histories`
- `update_search_history`
- `delete_search_history`
- `search`
=> feat(openapi): implement "search history" related OpenAPI functions

graviti/openapi/__init__.py, graviti/openapi/action.py
Add the following funcions:
- `create_action_run`
- `list_action_runs`
- `get_action_run`
- `cancel_action_run`
- `get_action_run_node_log`
=> feat(openapi): implement "action run" related OpenAPI functions

graviti/openapi/__init__.py, graviti/openapi/record.py
Add the following funcions:
- `list_draft_records`
- `list_commit_records`
- `add_records`
- `update_records`
- `delete_records`
=> feat(openapi): implement "record" related OpenAPI functions

docs/source/features/sheet_management/search.rst
- use `std.label.Box2D` to replace `points`
- use `Dataset.commit` to upload data rather than `Draft`
=> docs: refine the sample code in "sheet_management/search.rst"
