Graviti-AI/graviti-python-sdk

- graviti/schema/extractors.py
1. Fix the KeyError by changing the `vertices_keys` from `("x", "y",
"z")` to `("x", "y", "v").
2. Change the field name from `keypoints2d` to `keypoints2ds`.
> fix(schema): fix the Keypoints2D extractor related errors

- graviti/utility/typing.py
Protocol can be imported from typing only if python version >= 3.8
> fix(utility): fix ImportError produced by "Protocol" in "typing.py"

- graviti/schema/package.py
- "version" -> "revision"
- "partial_package" -> "subpackage"
- "repo" -> "url"
> style(schema): rename the improper variable names in "schema/package.py"

- graviti/manager/branch.py
- graviti/manager/commit.py
- graviti/manager/dataset.py
- graviti/manager/tag.py
If user save the variable manager like `commit_manager = dataset.commits`,
so when the dataset checkout to other commit, the commit_id in commit_manager
will not change. This will cause some problems.
> refactor(manager): use "dataset" to replace "access_info"

- graviti/utility/paging.py
https://docs.python.org/3/library/itertools.html#itertools.accumulate
The "initial" parameter is provided in python 3.8
> fix(utility): fix the invalid kwarg "initial" in "itertools.accumulate"

- graviti/dataframe/column/series.py
- graviti/dataframe/container.py
- graviti/dataframe/frame.py
- graviti/portex/__init__.py
- graviti/portex/base.py
- graviti/portex/builtin.py
- graviti/portex/register.py
- graviti/portex/template.py
The following classes are moved:
- `dataframe.container.ContainerRegister`
- `dataframe.container.ExternalContainerRegister`
- `portex.base.PyArrowConversionRegister`
> refactor: move register related classes into "portex/register.py"

- graviti/openapi/data.py
- graviti/openapi/sheet.py
- Reduce the possibility of conflicts when multiple users modify the data
- It will be more convenient to expand the interface later
> feat(openapi): use "__record_key" to locate data during transmission

- graviti/portex/builtin.py
No longer use Portex binary type to represent binary files.
> refactor(portex): return "pyarrow.binary" in "binary.to_pyarrow"

- graviti/utility/paging.py
```
ValueError: When passing an empty collection of arrays you must also
pass the data type
```
> fix(utility): fix the ValueError in to_pyarrow when PagingList is empty

- graviti/portex/package.py
The building order depends on the result of "Path.glob" method.
And the return order of "Path.glob" differs in different systems.
When the first building type depends on other unbuilt type, building
system will search that dependency type in the base package of the
"Imports" instance. But that time there are no types successfully
builded, the base package is an empty mapping. Which means the
search code "return self._package[key]" under the "if self._package:"
statement will be skipped and "KeyError" will be raised instead.
> fix(portex): fix the "KeyError" when building external package

- graviti/utility/file.py
The url of File on Windows is like "file:///C:/Users/image.jpg".
In "File._create", the "url[7:]" part is used to generate the new path,
and this result in an extra slash at the beginning of the path, which
makes the path invalid.
> fix(utility): fix the invalid path in "File._create" on Windows

- graviti/portex/template.py
| cases                  | before              | after              |
| ---------------------- | ------------------- | ------------------ |
| ob.label.Box2D()       | 153 µs ± 7.57 µs    | 122 µs ± 1.41 µs   |
| ob.label.Box3D()       | 273 µs ± 3.3 µs     | 246 µs ± 3.32 µs   |
> perf(portex): cache "Signature" for "PortexExternalType"

- graviti/portex/base.py
| cases           | before           | after            |
| --------------- | ---------------- | ---------------- |
| bdd100k.imports | 787 µs ± 9.05 µs | 249 µs ± 4.39 µs |
> perf(portex): use "getattr" to replace "hasattr" in "PortexType.imports"

- graviti/exception.py
- graviti/openapi/requests.py
When requesting to openAPI, there may be exceptions during transmission,
which leads to error response without "code" in content.
> fix(openapi): adapt to error response without "code" in content

- graviti/dataframe/column/series.py
Add support for "label.file.RemoteInstanceMask" and
"label.file.RemoteInstanceMask" in Project-OpenBytes/standard.
> feat(dataframe): add temporary support for instance and semantic mask

- graviti/dataframe/frame.py
- graviti/manager/draft.py
- graviti/manager/sheets.py
At the same time, the initialization of "DataFrame.operations" has been moved
from "_from_factory" to "Draft._init_dataframe".
> refactor: separate "_init_dataframe" from "_init_data" in class "Sheets"

- graviti/openapi/search.py
search_history_id -> search_id
limit default value: 128 -> all search results
> docs(openapi): modify the docstring of method "create_search"

- graviti/manager/draft.py
Reset DataFrame.operations instead of Draft._data:
- reduce redundant requests like "Get Sheet", "List Data"
- ensure that the DataFrame that the user get before "upload" can still be used
> refactor(manager): remove the reset _data operation in "Draft.upload"

- graviti/portex/builder.py
reference: https://github.com/pre-commit/pre-commit/blob/ \
44cb80f74ac95f347fd66e0eb8d432b7cee4ca83/pre_commit/git.py#L210
Note that the git config can still affect the calling of git within SDK.
> fix(portex): fix the error when running git with empty env on Windows

- graviti/portex/base.py
- graviti/portex/external.py
- graviti/portex/factory.py
Tests on box2d of VOC2012Detection.
| cases               | before           | after             |
| ---------------     | ---------------- | ----------------  |
| box2d.internal_type | 59.5 µs ± 104 ns | 54.1 µs ± 99.7 ns |
| box2d.to_builtin()  | 145 µs ± 14.5 µs | 124 µs ± 292 ns   |
| box2d._data         | 90.2 µs ± 113 ns | 80.5 µs ± 3.59 µs |
> perf(portex): use dict instead of **kwargs to pass args in factory

- graviti/manager/branch.py
When we get the branch "main" on a dataset without any commit history,
this error will be raised.
> fix(manager): fix NoCommitsError caused by "BranchManager.get"

- graviti/portex/builder.py
- graviti/portex/builtin.py
- graviti/portex/factory.py
- graviti/portex/param.py
Error message:
AttributeError: module 'graviti' has no attribute 'portex'
> fix(portex): fix the AttributeError when "import graviti" in Python3.6

- graviti/dataframe/column/series.py
- graviti/dataframe/container.py
- graviti/dataframe/frame.py
- graviti/dataframe/indexing.py
Not support '__delitem__' for the Series which is a member of a
DataFrame.
Not support 'loc.__delitem__' and 'iloc.__delitem__' for the DataFrame
which is a member of another DataFrame
> feat(dataframe): forbid deleting items by loc for non-root Containers

- graviti/exception.py
- graviti/manager/sheets.py
Field names in Graviti data platform is case insensitive, graviti
python SDK is case sensitive. These difference may cause confliction
when uploading local data to data platform.
> feat: check field name confliction in "Sheets._upload_to_draft"

- graviti/dataframe/column/series.py
example:
```python
In [10]: schema  # the array items is enum
Out[10]:
array(
items=enum(
values=['cat', 'dog'],
),
)
In [11]: data  # the first array is an empty list
Out[11]: [[], ['cat', 'dog'], ['cat', 'dog'], ['cat', 'dog']]
In [12]: Series(data, schema)  # creation fail
---------------------------------------------------------------------------
ArrowInvalid                              Traceback (most recent call last)
...
...
ArrowInvalid: Could not convert 'cat' with type str: tried to convert to int8
```
> fix(dataframe): fix Series creation fail when the array items is enum

- graviti/openapi/file.py
Error Message from S3:
"Invalid according to Policy: Extra input fields: signedrequestheaders"
> fix(openapi): fix "Extra input fields" error when uploading binary to s3

- graviti/manager/sheets.py
Use "keys", "values" and "items" of "dict" to replace the same methods
in "MutableMapping". The methods in "dict" provides a better print method.
> refactor(manager): add "keys", "values" and "items" in "Sheets"

- graviti/utility/common.py
Error message:
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
> fix(utility): fix the "fromisoformat" is not supported in Python3.6

- graviti/manager/search.py
- graviti/openapi/search.py
- graviti/openapi/storage_config.py
- graviti/utility/__init__.py
- graviti/utility/typing.py
The "sort" parameter is applied to the following openapi functions:
- `list_storage_configs`
- `list_search_histories`
- `list_search_records`
> refactor: apply "sort" parameter to three list openapi functions

- .github/workflows/pre-commit.yaml
"ruby/setup-ruby@v1" does not support ubuntu-20.04 anymore
> ci: set ubuntu version to "20.04" for "Pre-commit"
